Manager:
    Menu:
        name:'menu'
    Game:
        name:'game'

<Menu>:
    BoxLayout:
        Button:
            text: "Football Game"
            background_color : 0, 0, 1, 1
            on_press:
                # You can define the duration of the change
                # and the direction of the slide
                root.manager.transition.direction = 'left'
                root.manager.transition.duration = 1
                root.manager.current = 'game'
        Button:
            text: "Snake Game"
            background_color : 1, 1, 0, 1
            on_press:
                root.manager.transition.direction = 'left'
                root.manager.transition.duration = 1
                root.manager.current = 'screen_three'


<SoccerBall>:
    size: 50, 50 
    canvas:
        Ellipse:
            source: 'football.png'
            pos: 50,50
            size: self.size          

<SoccerPlayer>:
    size: 50, 50
    src: 'assets/player2run.png'
    anim_delay: 0.1
    canvas.before:
        Rectangle:
            pos:self.pos
            size:50,50
            source:self.src

<Game>:
    ball: soccer_ball
    player1: player_left
    player2: player_right
    allow_stretch:True
    canvas:
        Rectangle:
            pos: self.center_x-5, 0
            size: 1, self.height
    
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'field2.png'
    
    Label:
        font_size: 70  
        font_name: 'fonts/RobotoCondensed-BoldItalic.ttf'
        center_x: root.width / 4
        top: root.top - 50
        text: str(root.player1.score)
        
    Label:
        font_size: 70  
        font_name: 'fonts/RobotoCondensed-BoldItalic.ttf'
        center_x: root.width * 3 / 4
        top: root.top - 50
        text: str(root.player2.score)
    Label:
        font_size: root.width / 20
        font_name: 'fonts/CampusPersonalUse-dE27.ttf'
        center_x: root.center_x
        top: root.top - (root.height/10)
        text: 'PUMPS BALL GAME'
    SoccerBall:
        id: soccer_ball
        center: self.parent.center
        
    SoccerPlayer:
        id: player_left
        x: root.width*3/4
        center_y: root.center_y
        center_x: root.center_x
        
    SoccerPlayer:
        id: player_right
        src: 'assets/player1kick.png'
        x: root.width/3
        center_y: root.center_y
        center_x: root.center_x